### ISSUE TITLE
ids parameter is mandatory

### ISSUE THREAD

**Issue by Coroico** [Coroico/AdvSearch#1]
&ids parameter is required, otherwise no results are found.

**Comment by Coroico** [comment]
See commit 6cafc52

**Comment by rtripault** [comment]
Not sure that's the best place to discuss about that but, wouldn't it be better (more user friendly) to assume that if no value (or 0) is given to &ids then we want to search through all resources in the context(s) ? (yes, finally found some time to test-drive AdvSearch!!)
