### ISSUE TITLE
is there a way to disable the search for Symlinks/Weblinks ?

### ISSUE THREAD

**Issue by Coroico** [Coroico/AdvSearch#15]
No setting exists to disable the search in reference documents (symlinks & weblinks).

A future new parameter could be:

---- &hideLink [0 | 1] : Search in content of type reference   (optional)

```
    - 0 : search in content of document AND reference type
    - 1 : search only in content of document type (default)
```

**Comment by goldsky** [comment]
https://github.com/Coroico/AdvSearch/commit/4937d2e6640362e5d7a8979fbf8a94203e8b4fba
