### ISSUE TITLE
Multiple Selection Option for AdvSearch

### ISSUE THREAD

**Issue by seekdiver** [Coroico/AdvSearch#18]
Hi, is there a way to change the dropdownlist (single selection) to multiple selection choices, so that to pass multiple values to the function and return the results that matches the multiple selection values?

**Comment by Coroico** [comment]
This is already the case. You can define a multiple drop down list and use AdvSearch. AdvSearch manage the multiple list of values passed to the function.
As example, run the demo http://www.revo.wangba.fr/faceted-search-1.html  by choosing Chile and Indonesia as Tags. 
You get the results tagged with Chile and Indonesia only.
