### ISSUE TITLE
core/components/advsearch/model/advsearch/advsearch.class.php : 588) PHP warning: mb_strpos() [<a href='function.mb-strpos'>function.mb-strpos</a>]: Offset not contained in string

### ISSUE THREAD

**Issue by ghost** [Coroico/AdvSearch#3]
Hi, the component work fine but in the modx error log I see this error:

core/components/advsearch/model/advsearch/advsearch.class.php : 588) PHP warning: mb_strpos() [<a href='function.mb-strpos'>function.mb-strpos</a>]: Offset not contained in string

the code:

[[!AdvSearch?
  &ids=`[[GetIds? &ids=`c4,-4,-7,-8,-9,-10,-11,-12,-13`]]` 
  &init=`all`
  &perPage=`5`
  &includeTVs=`aTotal, barPropiedad, valPropiedad, zonaPropiedad, img001`
  &containerTpl=`ListaBoxtpl`
  &tpl=`Listatpl`
]]

System info:

Modx revo 2.1.3pl (traditional)
PHP version: 5.2.17

**Comment by Coroico** [comment]
Same error as issue #23
