### ISSUE TITLE
Allow Next & Prev links in pagingType 2

### ISSUE THREAD

**Issue by shaunmorrison** [Coroico/AdvSearch#33]
Hi, like pagingType 1 could we have next and prev links to add pageTpl for pagingType 2? Tried adding in, but showed blank.

**Comment by Coroico** [comment]
Not sure to understand you. Paging type 1 is different of paging type 2.
And paging type 2 doesn't use prev-next link.

See the difference on this demo page : http://www.revo.wangba.fr/paging-types.html

**Comment by shaunmorrison** [comment]
Yes, it would be nice to have full pagination features though e.g. Prev 1,2,3,4,5 Next – just like getPage. You could even have First and Last links in there as well. 

Thanks for your prompt reply.

**Comment by yongzhenlow** [comment]
@Coroico Hello, could you provide some insight on why there's 2 paging templates? 

Currently, my forked repo is running a version where I've deprecated the "paging<num>Tpl" parameter, and introduced a new "pagingTpl" chunk, which have all the relevant placeholders supplied, and thus giving more customizability. I've also added a [[+firstlink]] and [[+lastlink]] placeholder.

**Comment by Coroico** [comment]
Hello, could you provide some insight on why there's 2 paging templates? 

Because GetPage, is not the only answer and I have decided to offer two different type of pagination.
Run  http://www.revo.wangba.fr/paging-types.html to see the differences.

**Comment by yongzhenlow** [comment]
@Coroico I know, I am not asking for getPage compatibility. It seems like a single template would suffice.

See my repo, under production branch -> https://github.com/yzlow/AdvSearch

With this 1 template, the user can style an output that's the same as your current 2 templates.
