### ISSUE TITLE
No pagination controls if one page in pagingType 2

### ISSUE THREAD

**Issue by shaunmorrison** [Coroico/AdvSearch#34]
Hi, would it be possible to give the option to not show pagination controls on pagingType 2 if there is only one page of results. Currently pagination will tend to look strange if there is just the number '1' there.

**Comment by Coroico** [comment]
No so strange. If it exists only one page of results, it seems normal to display: Result pages: 1 

Try to search "villarica" on this demo page as example : http://www.revo.wangba.fr/paging-types.html

**Comment by shaunmorrison** [comment]
If you want consistency across your site with pagination and you are using getPage – this does not show pagination when there is only one page. It's a pretty nice option to have.
