### ISSUE TITLE
&ids not working with Articles

### ISSUE THREAD

**Issue by mewolari** [Coroico/AdvSearch#39]
I've added to my website:

[[!AdvSearch? 
&ids=`1,16`
]]

ID 16 is the articles container. 

AdvSearch is not able to search inside Articles when using &ids.

When I remove "&ids=`1,16`" everything is working fine, but I'm not able to hide certain pages from the searchresults.

1,16 is placed between `, but not displayed on github.

**Comment by Coroico** [comment]
&ids: Comma-delimited list of ids to search in.

Use GetIds ( http://modx.com/extras/package/getids) addon to specify complex list of ids. 

[[!AdvSearch?
&ids=`[[!GetIds? &ids=`1,c16`]]`
]]

And Yes, as Articles is a custom resource, probably AdvSearch doesn't search inside.  Never tested.

**Comment by mewolari** [comment]
Now everything is working fine. 

Thanks.

**Comment by Glidias** [comment]
Could state that the plugin isn't included by default and needs to be downloaded seperately in RTFM, otherwise one may assume it was already included....
