### ISSUE TITLE
"Undefined index: addCss" after upgrade to AdvSearch 1.0.1

### ISSUE THREAD

**Issue by anhuth** [Coroico/AdvSearch#40]
After upgrading AdvSearch from version 1.0.0 to 1.0.1, following notice appears after any search:

Notice: Undefined index: addCss in <path_to_core>/components/advsearch/model/advsearch/advsearch.class.php on line 357

I deinstalled Advsearch completely and reinstalled again, but this didn't help.

I commented out the indicated new line in code:
// if ($this->config['addCss'] == 1) $this->modx->regClientCss($this->config['assetsUrl'] . 'css/advsearch.css');

This helped, of course, but doesn't look like an eligible solution, since there was probably a good reason to insert that line.

**Comment by Coroico** [comment]
To fix this issue see commit 4fee690532

**Comment by anhuth** [comment]
Looks good. No Notice anymore since insertion of the fix. Thanks!
