### ISSUE TITLE
Add the ability to exclude certain resources and their children

### ISSUE THREAD

**Issue by oo12** [Coroico/AdvSearch#42]
Hi, thanks for this great extra!

It'd be nice if it had an &exclude property, similar to simpleSearch.  &exclude could be a comma-separated list of resource IDs exclude from the search.  Their children would also be excluded.

Sometimes there's a part of the resource tree which I don't want showing up in the search results. Yes, I could hide the resources from the menu and set hideMenu to 0, but I'm also using Articles and all blog posts are hidden (so &hideMenu=`0` effectively turns off search for a blog).

**Comment by Coroico** [comment]
By using the GetIds snippet ( http://modx.com/extras/package/getids ), you probably can solve your request.

Apologies, the demo site is still under construction. But the add-on description is in my opinion enough to understand how to use it.

**Comment by SnowCreative** [comment]
Adding the ability to exclude certain ids (not including children) is simple. I added this to line 36 of advsearch.mysql.controller.class.php in the controllers folder:

```
    // exclude ids
    if (!empty($this->config['exclude'])) {
        $excludeids = array_map('trim', @explode(',', $this->config['exclude']));
        $c->where(array(
            'modResource.id:NOT IN' => $excludeids
        ));
    }
```

Then I can use  
`&exclude='(ids here)'`

in the parameters
