### ISSUE TITLE
the search request "AdvSearch is" hangs the simple ajax test demo

### ISSUE THREAD

**Issue by manicko** [Coroico/AdvSearch#47]
Just found that some requests hangs the search, tried the demo http://www.revo.wangba.fr/simple-test-ajax.html
with request "AdvSearch is" and it hangs the search. (as i understand it is because of the second word shorter than allowed number of symbols)

There is another problem with search results output. The extract will not be shown if searched word is the first word in the searched fieald and starts with upper case. E.g. I have introtext: "Ranking champions League Semifinalists" and searching for ranking(lowercase), Than the word Ranking will not be shown in [[+extras]].

**Comment by goldsky** [comment]
this has been fixed on the upcoming update
