### ISSUE TITLE
PHP Notice: Undefined Index

### ISSUE THREAD

**Issue by fireproofsocks** [Coroico/AdvSearch#50]
PHP Notice:  Undefined index: addCss in core/components/advsearch/model/advsearch/advsearch.class.php on line 357

It's this line:
 if ($this->config['addCss'] == 1) $this->modx->regClientCss($this->config['assetsUrl'] . 'css/advsearch.css');

You need to check for that index being set, otherwise the logs start filling up with these notices.

Version 1.0.1-pl

**Comment by goldsky** [comment]
https://github.com/Coroico/AdvSearch/blob/Development/core/components/advsearch/model/advsearch/advsearchutil.class.php#L120
