### ISSUE TITLE
Empty script tag included when addJs=0 // possible fix

### ISSUE THREAD

**Issue by vierkantemeter** [Coroico/AdvSearch#67]
I don't want to include Js, JQuery and CSS, so I added:

&addCss=`0` &addJs=`0` &addJQuery =`0`

This works as it should, except an empty script tag is added to the bottom of the document, before the closing body tag. I think the problem is line 175 in core/components/advsearch/model/advsearch/advsearchform.class.php. I commented the following lines out and now the empty tag is no longer included:
            //else
                //$this->modx->regClientScript($jsHeader);

**Comment by goldsky** [comment]
You are right.
Thanx for reporting.
