### ISSUE TITLE
Placeholders for joined table are not set

### ISSUE THREAD

**Issue by vierkantemeter** [Coroico/AdvSearch#68]
I use a queryhook to search for users, including their profile (user attributes table). I made a queryhook for this. The searching works, but the placeholders for the fields from the joined table (for example 'city') do not work.

See http://forums.modx.com/thread/88954/advsearch-placeholders-for-joined-table-in-queryhook-are-not-set#dis-post-489153 for all the used code.

**Comment by goldsky** [comment]
At this time, I've added a &toArray param to the snippet.
This will available once I update the package.
With that param, you can see the whole placeholders you can use.
