### ISSUE TITLE
Extracts contain text behind search string in Polish

### ISSUE THREAD

**Issue by voluntas88** [Coroico/AdvSearch#70]
I use AdvSearch in site with Polish content. Search are working and it finds all occurances in text. But extracts from content are taken after couple sentences behind search string position is. I mean extract doesn't contain search string but takes text after found occurance. But some extracts contain search string. If to replace content with English text, AdvSearch is working perfect.
Is there some way to fix that issue? I think it is because special Polish characters, I use utf8 charset, multi-bytes is enabled
![img](https://cloud.githubusercontent.com/assets/1125297/2616913/2a9e5d18-bc0c-11e3-93b7-a46673a3f4a5.png)

**Comment by goldsky** [comment]
try 2.0.0-beta1
