### ISSUE TITLE
Is it possible to get demos & documentation online?

### ISSUE THREAD

**Issue by mtalvenheimo** [Coroico/AdvSearch#76]
Hi,
Trying to figure out how to make faceted search (Query Hook). Demos & documentation site is offline?
http://www.revo.wangba.fr/index.php?id=40

**Comment by absent42** [comment]
You can get the old docs from the Wayback Machine: https://web.archive.org/web/20130221070858/http://www.revo.wangba.fr/advsearch-documentation.html

**Comment by neoneddy** [comment]
I think we need to fork this project.  Seems like Corico is AWOL.

**Comment by goldsky** [comment]
I've been forking it for a while.
Look at the engine-controllers branch.
I just need to implement Zend Search back into this new branch, to make it compatible with the previous version.

**Comment by mtalvenheimo** [comment]
thhnx absent42 - nice tip :)
