### ISSUE TITLE
Wrong documentation concerning to Zend Framework files

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [Coroico/AdvSearch#78]
You write:
- http://rtfm.modx.com/extras/revo/advsearch
  
  > unzip you Zend package under the assets/libraries/ folder. This should create a subdirectory named "Zend" (assets/libraries/Zend) 
  > in this directory only the "search" directory and the "Exception.php" files are required. You could remove all the others files and directories. 
  > at the end you should have only the "Search" folder and the "Exception.php" file.
- https://github.com/Coroico/AdvSearch/blob/Development/core/components/advsearch/docs/advSearch101_v1.0.pdf
  
  > 4/ unzip you zend package under the assets/libraries/ folder. This should create a subdirectory named ‘Zend’ (assets/libraries/Zend)
  > 5/ in this directory  only the ‘search’ directory and the ‘Exception.php’ files are required. You could remove all the others files and directories.
  > At the end you should have something like this: http://i.imgur.com/JfEw0Wj.png

This is wrong. Search will not work and will error (or a blank page if php display errors off):
`Fatal error: require_once() [function.require]: Failed opening required 'Zend/Xml/Security.php' (include_path='.:/opt/php-5.2/lib/php:/home/www/assets/libraries/:/home/www/assets/libraries/') in /home/www/assets/libraries/Zend/Search/Lucene/Document/OpenXml.php on line 28`
Missing folder Xml!
Correctly will be:
 ![Correct](http://i.imgur.com/MrjTtL8.png)

This applies to ZendFramework-1.12.9-minimal (http://framework.zend.com/downloads/latest).

**Comment by jakub-gawryl** [comment]
Confirm on modx 2.3.3-pl.
Xml directory do the Job.

**Comment by humantex** [comment]
There has apparently been a major change to Zend's files repository, so the install docs are no longer vaild as the downloaded package uses a different file structure and file names with Lucene v. 1.12.17. The search functions are no longer contained in the main Zend library, so even the download location has changed for the now-seperate package.

Does advsearch still work correctly with the newest version of this v1 zend library, and if it does, what new files go where, and under what file names and folders?

**Comment by humantex** [comment]
As a reference... the location I found for the files is on Github: https://github.com/zendframework/ZendSearch

**Comment by goldsky** [comment]
the files are now included in 2.0.0-beta1
