### ISSUE TITLE
Documentation site is unavailable

### ISSUE THREAD

**Issue by Finetuned** [Coroico/AdvSearch#79]
The documentation site www.revo.wangba.fr is not available.

**Comment by vierkantemeter** [comment]
The developer stopped developing advsearch from what I know. You can view the site through the wayback machine: http://web.archive.org/web/20130419044802/http://www.revo.wangba.fr/advsearch-presentation.html

**Comment by vierkantemeter** [comment]
Related https://github.com/Coroico/AdvSearch/issues/76
