### ISSUE TITLE
2.0.0-beta1 installer warning

### ISSUE THREAD

**Issue by gadgetto** [Coroico/AdvSearch#82]
`Skipping vehicle object of class modPluginEvent (data object exists and cannot be upgraded); criteria: Array ( [pluginid] => 23 [event] => OnDocUnPublished ) 
Running PHP Resolver.
Could not load class: AdvSearch from advsearch.
Problem getting service advsearch, instance of class AdvSearch, from path /var/www/km/wwwRoot/core/components/advsearch/model/advsearch/`

AdvSearch installation finishes but I don't know if its installed correctly.

**Comment by goldsky** [comment]
It's a bug.
Meanwhile, you can keep using AdvSearch.
It's about checking Solr's folder.
If you don't use it, please **disable** AdvSearchSolr **plugin**
